version: "3.5"

services:
  # api:
  #   container_name: go-htmx
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   volumes: # needed for CompileDaemon to detect file changes
  #     - ./:/app
  #   depends_on:
  #     - db
  #   ports:
  #     - 5000:5000

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - gohtmxdata:/var/lib/postgresql/data

volumes:
  gohtmxdata: